### ISSUE TITLE
Support default skins

### ISSUE THREAD

**Issue by ZeProf2Code** [astei/crafthead#15]
Make so that we can get some default Steve skin instead of a HTTP 400 response.

**Comment by astei** [comment]
Apparently, even with the commit, it's not actually fetching the default skin. Need to investigate more, won't have the time for a few days though.

**Comment by astei** [comment]
And as I said that, I've fixed the issue at fault here.

**Comment by ZeProf2Code** [comment]
Thanks for the awesome service btw! 👍
