### ISSUE TITLE
CORS Issue

### ISSUE THREAD

**Issue by heychazza** [astei/crafthead#26]
Hi team,

Absolutely love the API, however when integrating this with Axios I get various CORS issues, is there any way you could correct this?

**Comment by astei** [comment]
"The team" is really just me. Do you have the CORS errors? What browser are you using? Not including this information helps nobody.

**Comment by heychazza** [comment]
> "The team" is really just me. Do you have the CORS errors? What browser are you using? Not including this information helps nobody.

Hi, using this with axios within a chromium browser would provide a CORS issue, I managed to apply a temporary fix by setting the headers with JSON.
