### ISSUE TITLE
dashed UUIDs

### ISSUE THREAD

**Issue by jkampich1411** [astei/crafthead#28]
I want to build a website where people can whitelist themselves. You put in your username and it requests the UUID from Crafthead. But the Whitelist plugin only supports UUID with dashes. Is there a way to get them?

**Comment by astei** [comment]
A Mojang UUID is nothing more than a standard UUID that has its hashes removed. All you have to do is put the dashes back in. This isn't difficult to achieve by yourself. [I literally had to write this code 5 years ago](https://github.com/tebexio/BuycraftX/blob/master/common/src/main/java/net/buycraft/plugin/UuidUtil.java#L19).
