### ISSUE TITLE
Avatars Rendering as Default

### ISSUE THREAD

**Issue by heychazza** [astei/crafthead#30]
Hey buddy,

It seems avatars have started rendering as the default now, for example;
- https://crafthead.net/avatar/ed6daf33575b460ba2f3e208a1004c10

In addition, ones on your website are too;
<img width="510" alt="Screnshot" src="https://user-images.githubusercontent.com/47271716/134773706-0d4026c6-7b79-4919-abde-a49d33e0815c.png">

Thank you.

**Comment by astei** [comment]
See #32, Cloudflare Workers is having issues communicating with the Mojang API and the problem is entirely out of my hands
