### ISSUE TITLE
Profile Endpoint Returning Fake JSON

### ISSUE THREAD

**Issue by heychazza** [astei/crafthead#31]
Hi,

The profile endpoint seems to be returning encoded JSON, https://crafthead.net/profile/ed6daf33575b460ba2f3e208a1004c10.
<img width="1293" alt="CleanShot 2021-09-25 at 3 09 28@2x" src="https://user-images.githubusercontent.com/47271716/134774423-183716f3-4211-4231-828e-8d5eb5f253a0.png">

Rather than an actual JSON object.

**Comment by astei** [comment]
When I tried this, it was returning "real" JSON
