### ISSUE TITLE
Manually Change Model

### ISSUE THREAD

**Issue by bribes** [astei/crafthead#48]
Add a way to manually change the model of the skin via url parameters?
Like ?model=slim ?model=classic

**Comment by TibiNonEst** [comment]
I can add this in pretty easily, just wondering what the use case is for this? Crafthead should choose the correct model automatically based on Minecraft's API texture response.

**Comment by bribes** [comment]
On my site I want to be able to manually change the model of a users skin since sometimes the skin model is correct according to API requests but it’s the wrong model for the skin itself.

**Comment by TibiNonEst** [comment]
Hm, makes sense, I would have thought Minecraft's API would be correct in terms of the model but I guess not.

**Comment by bribes** [comment]
Yeah sometimes if a user set the model of the skin to classic but the skin is suppose to be a slim model then it will show black bars behind and the skin in general will look weird.

**Comment by TibiNonEst** [comment]
Oh I see what you mean, will open a PR in a minute.

**Comment by bribes** [comment]
Thanks

**Comment by TibiNonEst** [comment]
On second thought, I'm tired and Cloudflare isn't liking me right now (grr), I'll do this tomorrow.
