### ISSUE TITLE
Wrap the Mojang API

### ISSUE THREAD

**Issue by DeJayDev** [astei/crafthead#9]
Having the Mojang API in cached Cloudflare workers helps plugin developers get the data they need at scale with a very low chance of the service going offline.

In particular, Crafthead would be very useful if it served skin textures and signatures as a JSON payload for the given username or UUID.

Example response for this endpoint:
```json
{
    "uuid": "606e2ff0-ed77-4842-9d6c-e1d3321c7838",
    "skin": {
        "url": "https://crafthead.net/skin/606e2ff0ed7748429d6ce1d3321c7838",
        "texture": "",
        "signature": ""
    }
}
```

Realistically, support for this [endpoint](https://wiki.vg/Mojang_API#UUID_-.3E_Profile_.2B_Skin.2FCape) is all Crafthead is in scope to provide.

**Comment by astei** [comment]
I will definitely consider this.
